# -*- coding: utf-8 -*-
"""CODSOFT2(ds).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104Fs6aDujUcFH8EOrbeCgtuWkyUH_73P
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

movie_data = pd.read_csv ('https://raw.githubusercontent.com/LearnDataSci/articles/master/Python%20Pandas%20Tutorial%20A%20Complete%20Introduction%20for%20Beginners/IMDB-Movie-Data.csv')
movie_data

label_encoders = {}
categorical_columns = ["Genre", "Director", "Actors",]

for col in categorical_columns:
    label_encoders[col] = LabelEncoder()
    movie_data[col] = label_encoders[col].fit_transform(movie_data[col])
label_encoders

X = movie_data.drop("Rating", axis=1)
y = movie_data["Rating"]
X
y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train
X_test
y_train
y_test

model = LinearRegression()
model

