# -*- coding: utf-8 -*-
"""codsoft4(ds).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlD7czTD-wl7cYmj485PwoJZx4ys6YIf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import math
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

df = pd.read_csv('https://raw.githubusercontent.com/pritom02bh/Car-Purchase-Amount-Prediction-Project-for-Car-Industry/master/Car_Purchasing_Data.csv', encoding = 'latin-1')
df

df.head()

df.shape

df.columns

df.describe()

df.describe(include = 'object')

df.columns

df.rename(columns = {
    'customer name': 'name',
    'customer e-mail': 'email_id',
    'annual Salary': 'salary',
    'credit card debt': 'debt',
    'net worth': 'net_worth',
    'car purchase amount': 'price'
}, inplace = True)

df.head(4)

df.isnull().sum()

df.duplicated().sum()

df.dtypes

df['Age'] = df['Age'].astype('int')

df.head()

df.drop(['Customer Name', 'Customer e-mail', 'Country'], axis = 1, inplace = True)

df.head()

sns.histplot(data = df, x = 'Annual Salary', kde = True)

plt.figure(figsize = (5,5))
sns.countplot(x = 'Gender', data = df)
plt.xticks([0,1], ['Female', 'Male'])

df['Gender'].value_counts()

plt.figure(figsize = (15, 5))
sns.countplot(data = df, x = 'Age')

figure, axes = plt.subplots(1, 2, figsize = (10,5))
sns.scatterplot(df['Annual Salary'], ax = axes[0])
sns.histplot(data = df, x ='Annual Salary', kde = True, ax = axes[1])

figure, axes = plt.subplots(1, 2, figsize = (10,5))
sns.scatterplot(df['Credit Card Debt'], ax = axes[0])
sns.histplot(data = df, x ='Credit Card Debt', kde = True, ax = axes[1])

figure, axes = plt.subplots(1, 2, figsize = (10,5))
sns.scatterplot(df['Net Worth'], ax = axes[0])
sns.histplot(data = df, x ='Net Worth', kde = True, ax = axes[1])

sns.jointplot(data = df, x = 'Annual Salary', y = 'Credit Card Debt', hue = 'Gender')
legend_handles = [plt.Line2D([0], [0], color = 'blue'), plt.Line2D([0], [0], color = 'orange')]
plt.legend(legend_handles, ['Feamle', 'Male'], title = 'Gender')

sns.jointplot(data = df, x = 'Annual Salary', y = 'Annual Salary', hue = 'Gender')
legend_handles = [plt.Line2D([0], [0], color = 'blue'), plt.Line2D([0], [0], color = 'orange')]
plt.legend(legend_handles, ['Feamle', 'Male'], title = 'Gender')

fig ,ax = plt.subplots(3,2,figsize=(10,4))
sns.boxplot(df, x = 'Age', ax = ax[0,0])
sns.boxplot(df, x = 'Annual Salary', ax = ax[0,1])
sns.boxplot(df, x = 'Credit Card Debt', ax = ax[1,0])
sns.boxplot(df, x = 'Net Worth', ax = ax[1,1])
sns.boxplot(df, x = 'Credit Card Debt', ax = ax[2,0])
fig.delaxes(ax = ax[2, 1])
ax[0,0].set_title('Age Boxplot')
ax[0,1].set_title('Salary Boxplot')
ax[1,0].set_title('Debt Boxplot')
ax[1,1].set_title('Net Worth Boxplot')
ax[2,0].set_title('Price Boxplot')
plt.tight_layout()
plt.show()